feat: strict bundle yaml validation
defenseunicorns/uds-cli pull request #596
Opened 2024-05-08 19:42 UTC by decleaver

## Description

Enables strict bundle validation

## Related Issue

Fixes #558 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-cli/blob/main/CONTRIBUTING.md) followed

2024-05-09 15:56 UTC, UncleGedd commented on src/pkg/utils/utils.go
> +func ReadYaml(path string, destConfig any) error {
Maybe `ReadYAMLStrict` vs `ReadYaml`?

2024-05-21 13:55 UTC, UncleGedd commented on src/pkg/utils/utils.go
> +	return goyaml.UnmarshalWithOptions(file, destConfig, goyaml.Strict())
Nice and simple! I've tried this with a couple of mistyped bundles and it works as expected. Noting that we could get fancier and use [validators](https://github.com/defenseunicorns/zarf/blob/29d3ee39dfcbe173405f6e0010cd0dfb9468cd6e/src/pkg/packager/lint/lint.go#L269) like how Zarf does it, but this solution is really simple and it works

2024-05-21 14:02 UTC, UncleGedd requested changes
In all the places where we return an error with `ReadYAMLStrict`, let's make the error msg more explicit about what went wrong, something like:
```
message.Fatalf(err, "Failed to read %s, error in YAML: %s", b.cfg.CreateOpts.BundleFile, err.Error())
```

2024-05-21 17:01 UTC, decleaver commented
> In all the places where we return an error with `ReadYAMLStrict`, let's make the error msg more explicit about what went wrong, something like:
> 
> ```
> message.Fatalf(err, "Failed to read %s, error in YAML: %s", b.cfg.CreateOpts.BundleFile, err.Error())
> ```

Updated the ReadYAMLStrict function to return more explicit error messaging

2024-05-21 20:10 UTC, UncleGedd commented
Couple of lingering merge conflicts and I think this one is g2g

2024-05-21 21:57 UTC, UncleGedd approved these changes

2024-05-21 21:57 UTC, merged